productGalleryLibrary:
  version: 1.x
  css: 
     theme:
        lib/smoothproducts.css: {}
  js:
     lib/smoothproducts.min.js: {}
     lib/product_gallery.js: {}     
  dependencies:
    - core/jquery
